### ISSUE TITLE
Is the database used for persisting the responses from FHIR calls?  [Question]

### ISSUE THREAD

**Issue by Matt2012** [Asymmetrik/graphql-fhir#37]
We are looking to at graphql-fhir as a way of acting as a middleware so that we can developers can write graphql to query out platform and return FHIR resources from a third party server. In this use case would we need a database? We don't want to store the results of the api calls.

#question

**Comment by Robert-W** [comment]
No you shouldn't need a database for that purpose. The necessity for a database really depends on your overall system. Some cases where you may want a database could be:

- Metrics. For performance and/or auditing reasons you may want to know who is doing what with which resources.
- Storing user information. If this is a simple middleware, this is probably handled elsewhere in your stack, otherwise, you could store any of the following:
  - user accounts
  - user sessions
  - job ids initiated by the user (if you support something like bulk FHIR)

We tried to develop this to be a simple lightweight middleware so that you won't need a database, and can connect to 3rd party servers easily, and authentication servers. However, if you want to turn this into something more, it can support that as well by simply forking it and adding any capabilities you want.
