### ISSUE TITLE
Need Help: add birthPlace Extension

### ISSUE THREAD

**Issue by vssiu33** [Asymmetrik/graphql-fhir#64]
When will a version supporting FHIR 4.0.1 be released? Is it possible to add the birthPlace extension into the patient schema?

http://hl7.org/fhir/R4/extension-patient-birthplace.html

**Comment by luan-dev** [comment]
Support for FHIR 4.0.1 is on our roadmap, but no ETA is available at this time. We currently offer support for 4.0.0 which includes the `patient-birthPlace` extension.

Extensions are supported in `extension.schema.js`. In the case of `patient-birthPlace`, you would put it in the `valueAddress` since it is of type address.

For more help, please look at #29
